### ISSUE TITLE
Intelligence game (2048)

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#139]
Using the 2048 game mechanic, game ideas:

- [ ] Varyn PWA game framework + CreateJS
- [ ] 2048
- [ ] Intelligencia - increasing intelligence level from Zoolander to Yoda
- [ ] Genetic Drift - from single cell to human

**Comment by DarkMatters** [comment]
Levels for Genetic Drift:

2 = single cell
4 = diplomonad (two-celled organism)
8 =   {hydra}
16 = {flagellates}
32 = {worm}
64 = {fish}
128 = Casineria kidd (reptile)
252 = Pleisadapis (I think this is a small mammal like predecessor)
512 = gorilla
1024 = Australopithecus
2048 = man

**Comment by DarkMatters** [comment]
Levels for Intelligencia:

2 = Homer
4 = Spicolli
8 = Gilligan
16 = The Dude
32 = Urkle
64 = Thelma
128 = McGuyver
252 = Einstein
512 = Stewie
1024 = Spock
2048 = Yoda
