### ISSUE TITLE
User favorite games API

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#151]
### User Favorite Games
Collect and maintain a user-based favorite games list. User must be logged in. This API only works on behalf of the current logged in user.

+ [x] UserFavoriteGamesAssign
+ [x] UserFavoriteGamesAssignList
+ [x] UserFavoriteGamesList
+ [x] UserFavoriteGamesDelete
+ [x] UserFavoriteGamesDeleteList: special case "*" clears the list
+ [x] UserFavoriteGamesMove

### Enginesis integration
+ [x] Procedures
+ [x] PHP API table
+ [x] PHP SDK
+ [x] JavaScript SDK
+ [x] Unit tests (PHP)
+ [ ] Deploy -l (PC, mac)
+ [ ] Deploy -q
+ [ ] Deploy LIVE

**Comment by DarkMatters** [comment]
Tested. Only need to deploy it. Also still need to check SDK sync,
