### ISSUE TITLE
API utilization tracking

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#162]
we should track API usage, by `site-id`, probably also by `game_id`. This new API should also indicate if a site_id is within the API access threshold by returning a `status_id` indicating:
  + within threshold: less than 95% of the site-defined api threshold limit in the current time period.
  + close: within 5% of the site-defined api threshold limit in the current time period.
  + over threshold at (or over) the site-defined api threshold limit in the current time period.

Will require adding a definition of the API threshold in the sites table and the sites configuration.

New table, `site_api_tracking`

new APIs
 + `SiteAPIRecord`
 + `SiteAPIList`

we add this in `index.php` for now. we can decide more details later.

**Comment by DarkMatters** [comment]
this is complete, further work to improve it in new issues #164
