### ISSUE TITLE
Can we remove jquery?

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#17]
Review the use of query and determine if we can get rid of it.

we are not using it for any compatibility reasons, we require IE 10 +

see http://youmightnotneedjquery.com/?mc_cid=e1ff606a1a&mc_eid=1119e6420c

JavaScript plugins and Function Repository:
https://plainjs.com/javascript/plugins/

**Comment by DarkMatters** [comment]
jquery is required by Bootstrap, otherwise it has been removed.
