### ISSUE TITLE
UserLoginCoreg API inconsistency

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#179]
Check API parameter usage it is inconsistent and should be changed. Not changing it now to not disrupt the SSO release but we should fix this.

+ [x] change avatarURL to avatar_url
+ [x] change idToken to id_token
+ [x] parameter order: network_id, site_user_id, user_name, real_name, email_address, gender, dob, agreement, scope, avatar_url, id_token
+ [x] PHP SDK
+ [x] JS SDK
+ [x] service table
+ [x] stored procedure

**Comment by DarkMatters** [comment]
we should complete this now as long as we are working on this code and updating the session logic

**Comment by DarkMatters** [comment]
code appears to all be there, not sure why this is still open.
