### ISSUE TITLE
Redirect for /avatar/

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#182]
setup a new redirect/rewrite for /avatar/ so we dont have to specify /avatar.php

/avatar/ should redirect to avatar.php

so should /avatar

**Comment by DarkMatters** [comment]
see https://serverfault.com/questions/45552/how-do-i-make-all-urls-run-through-a-single-php-file comments in accepted answer

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?q=$1 [L,QSA]
```

**Comment by DarkMatters** [comment]
Actually the redirect is not required because we already have the folder /avatar/ so just move avatar.php => /avatar/index.php and that works.

will need to add a redirect inside avatar.php to go to /avatar/index.php instead or load it so we can accommodate existing links.

**Comment by DarkMatters** [comment]
Test with
* http://enginesis.com/avatar.php?site_id=100&user_id=9999&size=1
* http://enginesis.com/avatar.php?site_id=106&user_id=10244&size=1
