### ISSUE TITLE
Home page and blog page promos from service call

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#184]
Currently the home page and blog page promos are hard-coded in HTML. The promos should be loaded via API call to `PromotionItemList`

Also requires promotion CMS working to define/edit promotion spots. http://www.enginesis-l.com/admin/procs/manage_promotions.php

**Comment by varyndev** [comment]
This is basically done, providing solutions in both enginesis.php and enginesis.js, allowing the promotion modules to be constructed either server-side or client-side.

What does remain to-do is setting up a separate promotion id and items for the blog page (this solution just reused the home page promotion id)
