### ISSUE TITLE
Upgrade server to Ubuntu 18

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#206]
Upgrade server to Ubuntu 16.04

```
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-86-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```

+ [ ] Create a new image from Rackspace control panel
+ [ ] back up dbs
+ [ ] copy scripts and config files
+ [ ] run upgrade.

### Notes

* PHP 7.0
* MySQL 5.7

**Comment by DarkMatters** [comment]
See release notes https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

**Comment by DarkMatters** [comment]
PHP migration: http://php.net/manual/en/migration70.php

MySQL migration: https://dev.mysql.com/doc/refman/5.7/en/upgrading.html

Backup databases and test on -l's first!

**Comment by DarkMatters** [comment]
Instructions from Ubuntu:
```
sudo apt-get update
sudo apt-get dist-upgrade
sudo do-release-upgrade
```

**Comment by varyndev** [comment]
should do this devops work along with #263

**Comment by DarkMatters** [comment]
we were unable to complete this on Rackspace. After several attempts and tickets and support there was no way to upgrade without provisioning a new instance, getting new IP addresses and migrating over to a new server. Since that's the same amount of work on Rackspace as anywhere else, we determines AWS was a cheaper option and we are bailing on Rackspace and moving over to AWS.

Changing this issue to migrate to AWS EC2 and RDS.

**Comment by DarkMatters** [comment]
AWS is up and running, just need to migrate the DNS to the new servers
