### ISSUE TITLE
Enginesis JS SDK: change callback to promise

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#218]
Change all the code in the enginesis SDK to return a promise.

Remove the callback parameter. THe only way to handle a response is to code the promise.

Leave the global callback. How do we reconcile calling the global callback **only** if the promise is not handled?

**Comment by DarkMatters** [comment]
we decided to keep the callback parameter for backward compatibility with existing code so no old games break.

**Comment by DarkMatters** [comment]
this is mostly done and working and we are using it in Inteligencia and game-frame
