### ISSUE TITLE
Coins coins coins!

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#222]
Setup coin earning events:

- [x] +20 for confirming email address. Include SSO.
- [x] +2 for playing any game the first time (games will have their own in-game coin earning events such as score, high-score, achievement, etc.)

- [x] Run email confirm procedure on all existing users who don't have it
- [x] verify all coins added are tracked and audited

**Comment by DarkMatters** [comment]
REMINDER: Coins have to be earned based on skill or determinate user actions. They cannot ever be earned by chance.

Therefore, scratch offs, slot machines, casino games based on random outcomes, cannot be used for earning coins. HOWEVER, if such games are built based on determinate circumstances, such as a seed input determines a specific outcome (recall how we built the World Winner games), then that has passed the "gambling" test in the past.

**Comment by DarkMatters** [comment]
This functionality is part of MVP. Users have no incentive to register and play games without this feature.

**Comment by varyndev** [comment]
The basic design for MVP is as follows:

### site_reward_currency_map
`site_reward_currency_map` table defines on a site-basis which events reward coins. 

### Event type id
Events are hard-coded string values used as keys. Application (business logic) looks up a reward based on this key. Initially we define keys for known reward events. A CMS page will allow site administrators to define new events. The companion table `reward_event_types` defines the reward event ids and provides a language-code lookup for localization.

### site-id
Which site defines this reward, allowing rewards to be site-specific. site-create logic will be updated to define the initial set of reward events for all new sites.

### amount
The number of coins to reward once the event is confirmed

### requires-content-type-id
A boolean 1/0 indicating a content type is required as part of this event. For example, if `content-type-id` is game, then a valid game-id is a required dependency to validating this event.

### content-type-id
An id from the `content-types` table that identifies the type of object associated with this event. For example, game-id

### site-reason
A text string indicating the reason for this event. This string is added to the history/audit record when the event is recorded (in addition to any local event reason data.)

### reward_event_types

This table defines the event-ids and organizes them by language-code.

Initial events:
+ REGCONFIRM: User registration confirmed
+ REGCONFIRMSSO: User confirmed registration with a network provider
+ INVITE: Reward for inviting another user to join
+ SIGNUP: Reward for registration from invite
+ INVITESIGNUP: Reward for invite resuling in a confirmed signup
+ GAMEPLAY: Reward for playing a game for the first time
+ GAMESHARE: Reward for sharing a game

**Comment by varyndev** [comment]
if user is logged in for `GameTrackingRecord` then earns +2
if user did not get game play coins then if submits score earns +2

updated procedure `ScoreSubmitInternal`

**Comment by varyndev** [comment]
the functionality for MVP is complete and deployed in production.
