### ISSUE TITLE
Set access control headers for images

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#223]
CORS is not set for non-PHP files served. In all apache .conf files add `Access-Control-Allow-Origin "*"`

` Header set Access-Control-Allow-Origin "*"`

then run

`apachectl -t`

`apachectl -k restart`

See https://enable-cors.org/server_apache.html

### Done and tested for:
- [x] -l on mac
- [x] -l on desktop PC
- [x] -q
- [x] production

**Comment by DarkMatters** [comment]
I'm not excited that we are allowing access * to the entire site. I thought we should just set this on images. Further research is needed to figure this out.

In enginesis index.php (service processor) we we adding a white-list concept to set access control header only if the referrer was allowed. That was never fully flushed out.
