### ISSUE TITLE
Game does not scale properly

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#242]
- [x] Game should scale to either 100% height of 100% width of client area of browser, depending on portrait or landscape. Seems to be an issue on certain mobile devices.

- [x] also physics is incorrect based on scale. 25% is too string and 100% is too weak, so probably need to scale all forces based on the game scale factor.

- [x] fix iframe resizer it is being set to height: 150 instead of height 100%

**Comment by varyndev** [comment]
Take a look at http://www.emanueleferonato.com/2018/02/16/how-to-scale-your-html5-games-if-your-framework-does-not-feature-a-scale-manager-or-if-you-do-not-use-any-framework/

**Comment by DarkMatters** [comment]
basic scaling issues have been resolved. The physics must be scaled to match the resolution.

The iframe issue was due to the game definition being a 7 (iframe) instead of 10 (canvas)
