### ISSUE TITLE
Replace PHP use of mcrypt

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#251]
mcrypt has been depreciated in PHP 7.2. It appears openssl is the replacement.

http://php.net/manual/en/function.mcrypt-encrypt.php

https://stackoverflow.com/questions/41272257/mcrypt-is-deprecated-what-is-the-alternative/41272680

https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly

See also: http://thefsb.tumblr.com/post/110749271235/using-opensslendecrypt-in-php-instead-of

**Comment by varyndev** [comment]
This should be addressed with issue #263

**Comment by DarkMatters** [comment]
Mostly completed via commit fde8bb1 and work on #22. Work remaining is to update live servers and deploy this version.
