### ISSUE TITLE
Improve Google Search for Varyn.com

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#253]
[Google search console](https://www.google.com/appserve/mkt/p/AIQrb_4NL3yZBotyGV8Csiu0am8I0HAYuzK6QzdVCOv3jvSeHDEQv6OdTz_PW0lB6Qi49el7E8HhUfa-K8uIIYzTBQtFzlwX4L8300XrAWk7_dQfFp9SDg1GMh-ZOMWOWeG2HKForAYEbdjCzdh5_LbSBb2o7rZ8L-0m8NUbyQu588Gq0mgJ-DGFkXQPB5-1Yh6k_vOclyenU-HAwILW_mn6Uru5I5zHSDYfyfHW-oFO341xY6eGbLbu) for improving SEO

verify and optimize correct setup.

Learn more details about [site verification](https://www.google.com/appserve/mkt/p/AIQrb_7IHgsjk2yYECN9IRgcF-sfkJyWSvB4-UZ4NGqUff9TSMSwgR5KMaJSAyU-OdEIqxc2giSIJJ_iaXdqYeMprKWcmWTYTi05t0W_qZCGAv0AKOwYVvBWIArhUJublPbYabVpREoj_hJiIMtPK-WicO89dzEA6zjngTEVXhFR5Bqc6oSNk9cMcFZQUH84py4tzEWFY_DauPVgg_ItayFgiI8TUnj6t5J7fistEbD2mUW7Dpjt6DGEdrP__b1HtpmM4wawpLs) and how to set permissions for other users.

1 | Add all your website versions - Make sure you add separate Search Console properties for all URL variations that your site supports, including https, http, www, and non-www. | Add a site
-- | -- | --
2 | Select your preferred version - Choose whether you want your site to appear with or without "www" in Google Search. | Set preferred version
3 | Select target country - Set your geographic preference if your site targets users in a specific country. | Choose country
4 | Share access with co-workers - If you want other people to access your error reports and search analytics in Search Console, add them with the appropriate access levels. | Manage site users
5 | Submit a [sitemap file](https://support.google.com/webmasters/answer/183668?hl=en) - This helps Google better understand how to crawl your site. | Submit a sitemap
6 | Learn how to work with Search Console - If you read only one document, this is it. | Using Search Console

**Comment by varyndev** [comment]
Create a site map page, generated from the site map file.

- [ ] sitemap.json can be the source. edit by hand for now, eventually generate it from a build CI script.
- [ ] sitemap.json generated sitemap.xml from CI script
- [ ] sitemap.json generates sitemap.html from CI script

**Comment by varyndev** [comment]
See https://www.npmjs.com/package/xml-js for XML JSON conversion

**Comment by varyndev** [comment]
Google topic on building and submitting a sitemap file: https://support.google.com/webmasters/answer/183668?hl=en

**Comment by varyndev** [comment]
The site map should also include an entry for each game, so that must be generated by script.

**Comment by varyndev** [comment]
Check out new sitemap.html and xml: 

http://varyn-l.com/sitemap/
http://varyn-l.com/sitemap.xml

For the sitemap to be complete, we need a way to iterate over all available games and add them into the games section.

**Comment by varyndev** [comment]
Generate a sitemap with `npm run sitemap`

**Comment by DarkMatters** [comment]
new version of robots.txt and sitemap.xml generated and deployed.
