### ISSUE TITLE
Migrate PHP to 7.0

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#263]
The major reason is to get openssl and other important security updates.

- [x] macOS
- [x] Windows 10
- [x] ubuntu 16

http://php.net/manual/en/migration70.php

https://www.quora.com/What-are-the-major-difference-between-PHP-5-and-PHP-7

**Comment by DarkMatters** [comment]
Recent developments require us to prioritize this issue. Will require 3 separate efforts:

- [ ] macOS
- [ ] Windows 10
- [ ] ubuntu 16

Update all documentation describing the migration tasks in `sitedev/documentation/system-administration/install-and-setup.md`

**Comment by DarkMatters** [comment]
Completed for macOS. install-and-setup doc was updated.

**Comment by DarkMatters** [comment]
Servers are all migrated to PHP 7

**Comment by varyndev** [comment]
crazy that this issue was part of the same milestone to update to php8. this project is taking too long!
