### ISSUE TITLE
Update platform error codes

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#267]
Add new error code `NO_MATCHING_ITEM`: "No matching item was identified"

Also to-do: review PHP, JavaScript code and make sure all error codes are documented in the error codes SQL tables.

Add maintenance procedure/admin php page to generate the error codes php and javascript code from the database table.

**Comment by varyndev** [comment]
new Admin proc added to Tools to generate error codes.
`NO_MATCHING_ITEM` added.
