### ISSUE TITLE
Show favorite games for logged in users

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#270]
A user who is logged in needs to see favorite games.

- [x] filled red heart for favorited, unfilled gray for unfavorited (acts as button)
- [x] on play page, user can favorite or unfavorite the game by tapping icon
- [x] in game cards, show favorite marker,  user can favorite or unfavorite the game by tapping icon
- [x] on profile page, show list of favorite games
- [x] add this ability in-game, not yet sure how, but maybe on the Options screen

**Comment by DarkMatters** [comment]
## Game Cards

<img width="383" alt="game card update" src="https://user-images.githubusercontent.com/5832539/40154238-40e9c2ce-5942-11e8-882c-4eefa086964f.png">

**Comment by DarkMatters** [comment]
Favorite game button implemented in-game in [intelligencia](https://github.com/VarynInc/inteligencia/issues/6)

**Comment by varyndev** [comment]
Added to play page via commit 9f99cc9adaf13ec653962dca1b4ca6813c8e8dda
