### ISSUE TITLE
Apply database updates and regenerate schema

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#271]
Next time schemadiffs is applied to live, take a fresh schema dump and compare to make sure enginesis_schema is completely up to date.

- [x] apply `schemadiffs.sql` and `procedures.sql` to live
- [x] dump database
- [x] load database on -q and load `procedures.sql`
- [x] load database on -l (windows and mac) and load `procedures.sql`
- [x] Either load database on -l to a new database and run Schema Comparison, or run Generate Schema Script to see which does a useful comparison

**Comment by varyndev** [comment]
schemas match.
