### ISSUE TITLE
Update website to Bootstrap 5

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#288]
Use the Bootstrap 4 css/design.

#### Get Bootstrap 4
https://getbootstrap.com/
https://getbootstrap.com/docs/4.0/getting-started/introduction/

#### Sample Bootstrap 4 design blocks
https://www.froala.com/design-blocks#playground
https://github.com/froala/design-blocks

**Comment by DarkMatters** [comment]
Changed to bs.5
