### ISSUE TITLE
Site deploy tool (local)

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#291]
We need a site deploy tool. Requirements:

+ compare the repo against the -d or the -q version of the site
+ never live, because the deploy script can only move -q to live
+ could also setup a git client and checkout master
+ must be able to delete files that have been removed
+ must be able to ignore files and folders
+ must work for all of our sites

In common with #279 

Issues:

+ currently we spend too much time figuring out which files have changed
+ sometimes files are missed
+ we update often, so this is taking a lot of time better spent on other tasks
+ this must be automated

**Comment by DarkMatters** [comment]
this is complete for now, while it could use some additional improvements.

Documented a bit in sitedev/documentation/system-administration/overview.md

run it with

```
npm run deploy -- [options]
```

check the doc for the options.
