### ISSUE TITLE
Create and setup missing domains (-l, -q)

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#296]
we need the -l domains so we can properly do SSL, including cURL, so it is going to be best to do it right and avoid self-signed which are untrusted.

- [x] godaddy setup missing domains:
  - enginesis-l.com
  - varyn-l.com
  - killerquiz-l.com
  - puttputtplanet-q.com
  - puttputtplanet-l.com
  - inxys-q.net
  - inxys-l.net
  - triviadome-q.net
  - triviadome-l.net
  - jumpydot-l.com
- [x] update apache configs
  - move logs to data/logs
  - setup -l sites
  - setup missing -q sites
- [x] update certbot
- [x] update locals (windows, osx) with hosts, apache configs, certs

**Comment by varyndev** [comment]
windows and macos setup and tested over SSL
