### ISSUE TITLE
Update all Email links to https

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#300]
Email links are all http.

- [x] http -> https
- [x] Copyright 2019
- [x] Remove Google +
- [x] create HTML-minifier process to automate this

**Comment by varyndev** [comment]
Let's also create a npm run process to automate this step.

https://www.npmjs.com/package/html-minifier

**Comment by varyndev** [comment]
started bin/update-email.js as `npm run update-email -- --site-id=106`

**Comment by DarkMatters** [comment]
this is done for Varyn (I did not do Enginesis)
Also includes new email Batch Update in the CMS.
