### ISSUE TITLE
Switch to Google Tag Manager

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#31]
GTM is supposedly much better than GA.

Get all website accounts/properties under a single account.
https://analytics.google.com/analytics/web/#/report-home/a13133265w27853995p26595636

Everything under Varyn account.

Remove Jumpydot.

https://developers.google.com/tag-manager/devguide

**Comment by varyndev** [comment]
Update to varyn.dev@gmail.com account

new tag/account: `G-YL1KFE561M`

Tag manager code:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YL1KFE561M"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YL1KFE561M');
</script>
```

**Comment by varyndev** [comment]
More info:

* More info: https://support.google.com/tagmanager/answer/6102821?hl=en&utm_id=ad
* Before install: https://support.google.com/tagmanager/answer/6103576
* Install: https://support.google.com/tagmanager/answer/6103696
* supported tags: https://support.google.com/tagmanager/answer/6106924

**Comment by DarkMatters** [comment]
effort is moving to issue #362
