### ISSUE TITLE
Update Google Plus links

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#310]
Pages and Emails have links to plus.google.com, we need to change these. Not sure to what, may just remove them.

**Comment by varyndev** [comment]
Removed from page footers.

**Comment by DarkMatters** [comment]
Removed `commonUtilities.shareOnGoogle`, need to verify any refs in JS source code.

**Comment by DarkMatters** [comment]
this appears to be complete, no refs found in Varyn or Enginesis source files.
