### ISSUE TITLE
Fix XSS attack vector

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#323]
Reported XSS attach. Verify all website inputs are sanitized before rendered on any page.

**Comment by varyndev** [comment]
There was on in the search field. Fixed.
Quick search and I cannot find any others, but still need deeper look.

**Comment by varyndev** [comment]
Test with the following input:

`?q=games+%3Cscript%3Ealert(%22Evil+strings%22);%3C/script%3E`

If the alert pops then the XSS succeeds.
