### ISSUE TITLE
Remove document.write from ad client

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#39]
Remove document.write! (I thought I already tried this:)
The ad.html uses it

```
var sNew = document.createElement("script");
sNew.async = true;
sNew.src = "https://example.com/script.min.js";
var s0 = document.getElementsByTagName('script')[0];
s0.parentNode.insertBefore(sNew, s0);
```
+ [ ] also check up with varyn.insertAndExecute()

**Comment by varyndev** [comment]
added new `commonUtilities.insertScriptElement`, use that

**Comment by DarkMatters** [comment]
I have to give up on this as it does not work. The updated code has to come from CPMStar as the write is inside the code they inject into the script.
