### ISSUE TITLE
After profile edit, reset token

### ISSUE THREAD

**Issue by Varyn9** [VarynInc/varyn#5]
After any form of user profile edit - change user name, change password, change email - upon successful save of new data we must regenerate the user's token.

I think a good approach is to add a generate token API, which given the current token, validate it, and if valid then generate a new token. 

We will need this also to refresh tokens every 24 hours.

Once tokens are refreshed update user last-login

+ [x] After profile edit, generate new token
+ [x] Log user in
+ [x] verify new token is good, and user last-login has been updated
+ [x] verify refresh in user-logged-in table

**Comment by varyndev** [comment]
This is necessary because the user can change their user_name, and user_name is part of the session token.

for an optimization, we could only refresh the token if the user_name changes.

**Comment by varyndev** [comment]
Moving to next milestone as it appears profile edit really does not work yet. Lots of placeholder code and TODO:s
