### ISSUE TITLE
Link Enginesis and Wordpress accounts

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#73]
Users should not have to login to wordpress if they have an enginesis account

- [ ] if authenticated user attempts to access a wordpress apge, they are automatically logged in
- [ ] create SSO function to automatically create wordpress account
- [ ] auto-login to wordpress

see https://codex.wordpress.org/Function_Reference/wp_signon

**Comment by varyndev** [comment]
Hold on this pending decision on #91 
If we remove WP and use our own comment system it would save significant effort here.

**Comment by DarkMatters** [comment]
no longer needed
